language: python
python:
  - 3.5
addons:
  postgresql: "9.4"
  firefox: "45.0"
services:
  - postgresql
  - redis-server
# before_install:
# - sudo apt-get update --fix-missing
# - sudo apt-get install -qq xserver-xephyr scrot xvfb tightvncserver
install:
  - sudo pip3 install pip3 --upgrade
  - sudo pip3 install setuptools --upgrade
  - sudo pip3 install zc.buildout
  - echo -e "[buildout]\nextends = profiles/development.cfg\n" > buildout.cfg
  - buildout -Nv -q -t 10
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - psql -c 'create database enkiblog_test;' -U postgres
  - tar -xjf /tmp/firefox-45.0.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - echo "Using firefox version `firefox --version`"
script:
  - bin/test
