language: python
python:
  - "3.5"

addons:
  postgresql: "9.4"
  firefox: "45.0"

services:
  - postgresql
  - redis-server

install:
  - pip install pip --upgrade
  - pip install setuptools --upgrade
  - pip install zc.buildout
  - echo -e "[buildout]\nextends = profiles/development.cfg\n" > buildout.cfg
  - buildout -Nv

# http://stackoverflow.com/questions/39279651/connection-refused-when-running-selenium-tests-in-marionette
#  - npm install -g geckodriver

# https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - tar -xjf /tmp/firefox-45.0.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - echo "Using firefox version `firefox --version`"
  - psql -c 'create database enkiblog_test;' -U postgres

script:
  - bin/test
