language: python
before_install:
- openssl aes-256-cbc -K $encrypted_a0a419e2d994_key -iv $encrypted_a0a419e2d994_iv
  -in kittycat.jpg.enc -out kittycat.jpg -d
- chmod 600 kittycat.jpg
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.18.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
python:
- 3.5
addons:
  postgresql: '9.4'
  firefox: '45.0'
  ssh_known_hosts: enkidulan.tk
services:
- postgresql
- redis-server
install:
- pip install pip --upgrade
- pip install setuptools --upgrade
- pip install zc.buildout
- echo -e "[buildout]\nextends = profiles/test.cfg\n[config_file]\nsqlalchemy_url
  = postgresql://postgres@localhost/enkiblog_test\n" > buildout.cfg
- buildout -Nv -q -t 10
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- psql -c 'create database enkiblog_test;' -U postgres
- tar -xjf /tmp/firefox-45.0.tar.bz2 --directory /tmp
- export PATH="/tmp/firefox:$PATH"
- echo "Using firefox version `firefox --version`"
script:
- bin/test
after_success:
- ssh blog@enkidulan.tk -i kittycat.jpg 'sh ./enkiblog_upgrade.sh'
